//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.Valtech.AuditService
{
    public enum AuditVendorId
    {
        VALTECH = 1,
        SABRE = 4,
        NPS = 2,
        VTOL = 3,
        ARSA_SVR_JBOSS = 5,
        MITROL = 6,
    }

    public enum AuditOperationType
    {
        PURCHASE = 1,
        PAYMENT_NOTIFICATION = 2,
        PAYMENT_ANULATION = 3,
        PROMO = 4,
        PAYMENT_REFUND = 5,
        FRAUD = 6,
        TOKEN = 7,
        SABRE_CREATE_SESSION = 8,
        SABRE_GET_RESERVATION = 9,
        SABRE_COMMAND = 10,
        SABRE_END_TRANSACTION = 11,
        SABRE_CLOSE_SESSION = 12,
        SABRE_ADD_TBM = 13,
        SABRE_EXCEPTION = 14,
        IVR_GET_CREDITCARD = 15,
        EMD = 16,
        IVR_GET_ID_ITX = 17,
        VOID = 18,

    }


}