//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.StructsComunicacionPOS
{
    public struct vpiBatchCloseDataOut_t
	{
		public short recIndex
		{
			get;
			set;
		}

		public string acquirerCode
		{
			get;
			set;
		}

		public string BatchNumber
		{
			get;
			set;
		}

		public string issuerCode
		{
			get;
			set;
		}

		public string purchaseCount
		{
			get;
			set;
		}

		public string purchaseAmount
		{
			get;
			set;
		}

		public string voidCount
		{
			get;
			set;
		}

		public string voidAmount
		{
			get;
			set;
		}

		public string refundCount
		{
			get;
			set;
		}

		public string refundAmount
		{
			get;
			set;
		}

		public string refvoidCount
		{
			get;
			set;
		}

		public string refvoidAmount
		{
			get;
			set;
		}

		public string date
		{
			get;
			set;
		}

		public string time
		{
			get;
			set;
		}

		public string terminalID
		{
			get;
			set;
		}

	}
}

