//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.StructsComunicacionPOS
{
    public struct vpiComParams_t
	{
		public string com
		{
			get;
			set;
		}

		public short baudRate
		{
			get;
			set;
		}

		public short byteSize
		{
			get;
			set;
		}

		public byte parity
		{
			get;
			set;
		}

		public short stopBits
		{
			get;
			set;
		}

	}
}

