//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.StructsComunicacionPOS
{
    public struct vpiIssuerOut_t
	{
		public short recIndex
		{
			get;
			set;
		}

		public string acquirerCode
		{
			get;
			set;
		}

		public string issuerCode
		{
			get;
			set;
		}

		public string issuerName
		{
			get;
			set;
		}

		public string maxInstCount
		{
			get;
			set;
		}

		public string terminalID
		{
			get;
			set;
		}

	}
}

