//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.StructsComunicacionPOS
{
    using System;

    public struct vpiPurchaseIn_t
	{
		public string Amount
		{
			get;
			set;
		}

		public string receiptNumber
		{
			get;
			set;
		}

		public string instalmentCount
		{
			get;
			set;
		}

		public string issuerCode
		{
			get;
			set;
		}

		public string planCode
		{
			get;
			set;
		}

		public string tip
		{
			get;
			set;
		}

		public string merchantCode
		{
			get;
			set;
		}

		public string merchantName
		{
			get;
			set;
		}

		public string Cuit
		{
			get;
			set;
		}

		public Byte linemode
		{
			get;
			set;
		}

	}
}

