//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.StructsComunicacionPOS
{
    public struct vpiTrxOut_t
    {
        public string hostRespCode
        {
            get;
            set;
        }

        public string hostMessage
        {
            get;
            set;
        }

        public string AuthCode
        {
            get;
            set;
        }

        public string TicketNumber
        {
            get;
            set;
        }

        public string BatchNumber
        {
            get;
            set;
        }

        public string customerName
        {
            get;
            set;
        }

        public string panFirst6
        {
            get;
            set;
        }

        public string panLast4
        {
            get;
            set;
        }

        public string date
        {
            get;
            set;
        }

        public string time
        {
            get;
            set;
        }

        public string terminalID
        {
            get;
            set;
        }

        public vpiTrxOut_t(bool inicializar)
            : this()
        {
            if (inicializar)
            {
                hostRespCode = new string('\0', 3);
                hostMessage = new string('\0', 33);
                AuthCode = new string('\0', 7);
                TicketNumber = new string('\0', 8);
                BatchNumber = new string('\0', 4);
                customerName = new string('\0', 27);
                panFirst6 = new string('\0', 7);
                panLast4 = new string('\0', 5);
                date = new string('\0', 11);
                time = new string('\0', 9);
                terminalID = new string('\0', 9);
            }
        }

    }
}

