//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.StructsComunicacionPOS
{
    public struct vpiVoidIn_t
	{
		public string OriginalTicket
		{
			get;
			set;
		}

		public string issuerCode
		{
			get;
			set;
		}

		public string merchantName
		{
			get;
			set;
		}

		public string Cuit
		{
			get;
			set;
		}

	}
}

