//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using CodenameNightwing.BusinessLogic;
using CodenameNightwing.Config;
using System.Xml;
using System;
using CodenameNightwing.Autorization;

namespace CodenameNightwing.WebServices.WSEspecificos
{
    public class WebServiceTarjetas : WebServiceBase
    {

        private string autorizador = null;

        protected override void writeQuery()
        {
            XmlDocument parser = new XmlDocument();
            parser.LoadXml(Configuration.getInstance().schemaWsTarjetas);
            XmlNode raiz = parser.DocumentElement;
            XmlNamespaceManager nsmgr = new XmlNamespaceManager(parser.NameTable);
            nsmgr.AddNamespace("soapenv", "http://schemas.xmlsoap.org/soap/envelope/");
            nsmgr.AddNamespace("ws", "http://ws.objects.binesws.interact.aerolineas.com.ar/");
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:getCCcashier/arg0", nsmgr).InnerText = autorizador;
            request = raiz.OuterXml;
        }

        protected override void setDireccion()
        {
            switch (Configuration.getInstance().environment)
            {
                case "QA":
                    direccion = Configuration.getInstance().dirServQa + Configuration.getInstance().serverTarjetas.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "PROD":
                    direccion = Configuration.getInstance().dirServProd + Configuration.getInstance().serverTarjetas.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "DEV":
                    direccion = Configuration.getInstance().dirServDev + Configuration.getInstance().serverTarjetas.Replace("|environment|", Configuration.getInstance().environment);
                    break;
            }
        }

        public WebServiceTarjetas()
        {
            AutorizatorFactory.getAutorizator();
            autorizador = (Configuration.getInstance().tipoAuth == TipoAutorizador.NPS) ? "NPS" : "ING";
            setup();
        }
    }
}
