//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using CodenameNightwing.Config;
using System.Xml;
using System;

namespace CodenameNightwing.WebServices.WSEspecificos
{
    public class WebServiceObtenerCuit : WebServiceBase
    {
        private string tipo
        {
            get;
            set;
        }

        private string documento
        {
            get;
            set;
        }

        protected override void writeQuery()
        {
            XmlDocument parser = new XmlDocument();
            parser.LoadXml(Configuration.getInstance().schemaWsObtenerCuit);
            XmlNode raiz = parser.DocumentElement;
            XmlNamespaceManager nsmgr = new XmlNamespaceManager(parser.NameTable);
            nsmgr.AddNamespace("soapenv", "http://schemas.xmlsoap.org/soap/envelope/");
            nsmgr.AddNamespace("ws", "http://ws.objects.binesws.interact.aerolineas.com.ar/");
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:generateCuit/arg0", nsmgr).InnerText = documento;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:generateCuit/arg1", nsmgr).InnerText = tipo;
            request = raiz.OuterXml;
        }

        protected override void setDireccion()
        {
            switch (Configuration.getInstance().environment)
            {
                case "QA":
                    direccion = Configuration.getInstance().dirServQa + Configuration.getInstance().serverCuitCuil.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "PROD":
                    direccion = Configuration.getInstance().dirServProd + Configuration.getInstance().serverCuitCuil.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "DEV":
                    direccion = Configuration.getInstance().dirServDev + Configuration.getInstance().serverCuitCuil.Replace("|environment|", Configuration.getInstance().environment);
                    break;
            }
        }

        public WebServiceObtenerCuit(string tipo, string documento)
        {
            this.tipo = tipo;
            this.documento = documento;
            setup();
        }
    }
}
