//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using CodenameNightwing.Config;
using System.Xml;
using System;
using System.Xml.Linq;

namespace CodenameNightwing.WebServices.WSEspecificos
{
    public class WebServiceUser : WebServiceBase
    {
        private string confKey = null;

        protected override void writeQuery()
        {
            XmlDocument parser = new XmlDocument();
            parser.LoadXml(Configuration.getInstance().schemaWsGetConfiguration);
            XmlNode raiz = parser.DocumentElement;
            XmlNamespaceManager nsmgr = new XmlNamespaceManager(parser.NameTable);
            nsmgr.AddNamespace("soapenv", "http://schemas.xmlsoap.org/soap/envelope/");
            nsmgr.AddNamespace("ws", "http://ws.objects.binesws.interact.aerolineas.com.ar/");
            raiz.SelectSingleNode("soapenv:Body/ws:getConfigurationValue/arg0", nsmgr).InnerText = this.confKey;
            request = raiz.OuterXml;
           /* logger.Info("request 1: " + request);
            string reqString = XElement.Parse(raiz.OuterXml).ToString();
            request = reqString;
            logger.Info("request 2: " + request);
            */
        }

        protected override void setDireccion()
        {
            switch (Configuration.getInstance().environment)
            {
                case "QA":
                    direccion = Configuration.getInstance().dirServQa + Configuration.getInstance().serverUser.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "PROD":
                    direccion = Configuration.getInstance().dirServProd + Configuration.getInstance().serverUser.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "DEV":
                    direccion = Configuration.getInstance().dirServDev + Configuration.getInstance().serverUser.Replace("|environment|", Configuration.getInstance().environment);
                    break;
            }
        }

        public WebServiceUser( string confKey)
        {
            this.confKey = confKey;
            setup();
        }
    }
}
