//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using CodenameNightwing.Config;
using System.Xml;
using System;
using CodenameNightwing.BusinessLogic;

namespace CodenameNightwing.WebServices.WSEspecificos
{
    public class WebServiceTerminal : WebServiceBase
    {

        private Terminal terminal
        {
            get;
            set;
        }

    protected override void writeQuery()
        {
            XmlDocument parser = new XmlDocument();
            parser.LoadXml(Configuration.getInstance().schemaWsinsertTerminal);
            XmlNode raiz = parser.DocumentElement;
            XmlNamespaceManager nsmgr = new XmlNamespaceManager(parser.NameTable);
            nsmgr.AddNamespace("soapenv", "http://schemas.xmlsoap.org/soap/envelope/");
            nsmgr.AddNamespace("ws", "http://ws.objects.binesws.interact.aerolineas.com.ar/");
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/base", nsmgr).InnerText = terminal.baseArsa;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/caja", nsmgr).InnerText = terminal.caja;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/pinpadId", nsmgr).InnerText = terminal.pinpadId;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/printerId", nsmgr).InnerText = terminal.printerId;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/sucursal", nsmgr).InnerText = terminal.sucursal;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/macAddress", nsmgr).InnerText = terminal.macAddress;
            raiz.SelectSingleNode("/soapenv:Envelope/soapenv:Body/ws:insertTerminal/arg0/machineName", nsmgr).InnerText = terminal.machineName;
            request = raiz.OuterXml;
        }

        protected override void setDireccion()
        {
            switch (Configuration.getInstance().environment)
            {
                case "QA":
                    direccion = Configuration.getInstance().dirServQa + Configuration.getInstance().serverTerminales.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "PROD":
                    direccion = Configuration.getInstance().dirServProd + Configuration.getInstance().serverTerminales.Replace("|environment|", Configuration.getInstance().environment);
                    break;
                case "DEV":
                    direccion = Configuration.getInstance().dirServDev + Configuration.getInstance().serverTerminales.Replace("|environment|", Configuration.getInstance().environment);
                    break;
            }
        }


        public WebServiceTerminal(Terminal terminal):base()
        {
            this.terminal = terminal;
            setup();
        }
    }
}
