//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.BusinessLogic
{
    public class Comercio
    {
        /// <summary>
        /// Cod Tarjeta para la transaccion
        /// </summary>
        private string _codigoTarjetaTrans;
        public string codigoTarjetaTrans
        {
            get { return _codigoTarjetaTrans; }
            set { _codigoTarjetaTrans = value; }
        }

        private string _codigoComercio;
        public string codigoComercio
        {
            get { return _codigoComercio; }
            set { _codigoComercio = value; }
        }
    }
}

