//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text;

namespace CodenameNightwing.BusinessLogic
{
    public class Emd
    {
        private string _descripcion;
        public string descripcion
        {
            get { return _descripcion; }
            set { _descripcion = value; }
        }

        private decimal _fare;
        public decimal fare
        {
            get { return _fare; }
            set { _fare = value; }
        }

        private int _codEmd;
        public int codEmd
        {
            get { return _codEmd; }
            set { _codEmd = value; }
        }

/*
                          <emds>
                     <codEmd>2</codEmd>
                     <!--Optional:-->
                     <descripcion>pepe</descripcion>
                     <fare>200.00</fare>
                  </emds>*/
        public string toXMLOperacion()
        {
            StringBuilder xmlOutput = new StringBuilder();

            xmlOutput.Append("<emds>");
            xmlOutput.Append("<codEmd>" + codEmd + "</codEmd>");
            xmlOutput.Append("<descripcion>" + descripcion + "</descripcion>");
            xmlOutput.Append("<fare>" + fare + "</fare>");
            xmlOutput.Append("</emds>");

            return xmlOutput.ToString();

        }
    }
}
