//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.BusinessLogic
{
    public enum TipoTransaccion
    {
        COMPRA = 1,
        CIERRE = 4,
        ANULACION = 2,
        DEVOLUCION = 3,
        NADA = 0,
    }

    public enum TipoOperacion
    {
        COMPRA_PASAJE = 1,
        COMPRA_SOLO_EMD = 2,
        CANJE = 3,
        DEVOLUCION = 4,
        ANULACION = 5,
        NADA = 0,
    }

    public enum TipoEstadoTransaccion
    {
        CREADA = 0,
        CONFIRMADA = 1,
        IMPRIMIENDO = 3,
        REVERSADA = 4,
        FALLIDA = 5,
        PROCESANDO = 6,
        CUPONES_IMPRESOS = 7,
        REVISE_PINPAD = 8,
        TARJETA_LEIDA = 9,
        PASANDO_INFO_INTERACT = 10,
        PREPARANDO_DATOS = 11,
        OBTENIENDO_DATOS = 12,
        OBTENIENDO_PROMOCIONES = 13,
        AGREGANDO_FOP = 14,
        ANALIZANDO_FRAUDE = 15,
        NADA = -1,
    }

    public enum TipoModoTransaccion
    {
        OFFLINE = 0,
        ONLINE = 1,
        OFFHOST = 3,
        NADA = -1,
    }

    public enum TipoAutorizador
    {
        POS_INGENICO = 1,
        HASAR,
        VTOL,
        VTOL_CALLCENTER,
        NPS,
        NADA = 1,
    }


    public enum TipoPrinter
    {
        EPSON,
        GPRINTER,
        EPSON_NATIVE,
        NADA = 0,
    }

    public enum TipoTarjeta
    {
        CREDITO,
        DEBITO,
        PASAJERO_FRECUENTE,
        CUENTA_CORRIENTE,
        SUBLO,
        EFECTIVO,
        CREDITO_DEBITO,
        NADA = 0,
    }

    public enum Procedencia
    { 
        NACIONAL,
        EXTRANJERO,
        PREGUNTAR
    }

    public enum TipoIngresoTarjeta
    {
        BAND = 1,
        EMV = 2,
        MANUAL = 3,
        FALLBACK = 4,
        IVR = 5,
        QR = 6,
        CONTACTLESS = 7,
        FORM_3P = 8
    }

    public enum TipoTransImpFallida
    {
        REIMPRESION = 1,
        ANULACION_OK = 2,
        TRANS_REVERSADA = 3,
        NO_COMPLETADA = 4,
        IMPRESION_OK = 5
    }

    public enum TipoSeleccionIVR
    {
        DERIVAR_IVR = 1,
        MANUAL = 2,
        CANCELAR = 3,
        ENLACE = 4
    }

    public enum TipoSeleccionEnlace
    {
        COPIAR_TEXTO = 1,
        COPIAR_ENLACE = 2,
        VERIFICAR = 3,
        CANCELAR = 4
    }

    public enum TipoWCentrixStatus
    {
        EN_PROCESO,
        VOLVER_A_AGENTE,
        CORTE_DE_LLAMADO,
        BIN_INCORRECTO,
        CANT_CAR_CC_INCORRECTO,
        FECHA_VENCIMIENTO_ERROR,
        CVC_ERROR,
        FINALIZADO_OK,
        FALLA_GRAL,
        TIMEOUT,
        DESCONOCIDO,
        CORTE_MANUAL

    }


    public enum TipoMitrolField
    {
        NUMERO_TARJETA,
        FECHAEXP,
        CVC,
        STATUS
    }

    public enum TipoIdiomaIVR
    {
        ESPAÑOL = 1,
        INGLES = 3,
        PORTUGUES = 2
    }


    public enum TipoMensaje
    {
        ERROR,
        WARNING,
        INFO
    }
}