//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.BusinessLogic
{
    public class Pais
    {
        private string _codigoPais;
        public string codigoPais
        {
            get { return _codigoPais; }
            set { _codigoPais = value; }
        }

        private string _descripcionPais;
        public string descripcionPais
        {
            get { return _descripcionPais; }
            set { _descripcionPais = value; }
        }
        public Pais(string codigo, string descripcion)
        {
            codigoPais = codigo;
            descripcionPais = descripcion;
        }

        public Pais() { }

        public override string ToString()
        {
            return descripcionPais;
        }
    }
}
