//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Text;

namespace CodenameNightwing.BusinessLogic
{
    public class Pasajero
    {
        private string _nombre;
        public string nombre
        {
            get { return _nombre; }
            set { _nombre = value; }
        }

        private List<Emd> _emds;
        public List<Emd> emds
        {
            get { return _emds; }
            set { _emds = value; }
        }

        private string _tipoPax;
        public string tipoPax
        {
            get { return _tipoPax; }
            set { _tipoPax = value; }
        }

        private decimal _fare;
        public decimal fare
        {
            get { return _fare; }
            set { _fare = value; }
        }

        public decimal getTotalPax()
        {
            decimal auxValor = 0.0M;
            auxValor += fare;
            foreach (Emd aux in emds)
            {
                auxValor += aux.fare;
            }
            return auxValor;
        }

        public decimal getTotalEmd()
        {
            decimal auxValor = 0.0M;
            foreach (Emd aux in emds)
            {
                auxValor += aux.fare;
            }
            return auxValor;
        }

        public Pasajero()
        {
            nombre = "";
            emds = new List<Emd>();
            tipoPax = "";
            fare = 0.0m;
        }

        /*
         * 
         * <pasajeros>
                  <!--Zero or more repetitions:-->
                  <emds>
                     <codEmd>2</codEmd>
                     <!--Optional:-->
                     <descripcion>pepe</descripcion>
                     <fare>200.00</fare>
                  </emds>
                  <emds>
                     <codEmd>1</codEmd>
                     <!--Optional:-->
                     <descripcion>pepe 2</descripcion>
                     <fare>100.00</fare>
                  </emds>

                  <fare>200.00</fare>
                  <!--Optional:-->
                  <nombre>PEPE</nombre>
                  <!--Optional:-->
                  <tipoPax>ADT</tipoPax>
               </pasajeros>*/

        public string toXMLOperacion()
        {
            StringBuilder xmlOutput = new StringBuilder();

            xmlOutput.Append("<pasajeros>");
            if ( emds != null) { 
                foreach ( Emd emd in emds)
                {
                    xmlOutput.Append( emd.toXMLOperacion() );
                }
            }
            xmlOutput.Append("<fare>" + fare + "</fare>");
            xmlOutput.Append("<nombre>" + nombre + "</nombre>");
            xmlOutput.Append("<tipoPax>" + tipoPax + "</tipoPax>");
            xmlOutput.Append("</pasajeros>");

            return xmlOutput.ToString();

        }

    }
}
 