//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.BusinessLogic
{
    public class PuntoDeAutorizacion
    {
        private string _sucursal;
        public string sucursal
        {
            get { return _sucursal; }
            set { _sucursal = value; }
        }

        private string _caja;
        public string caja
        {
            get { return _caja; }
            set { _caja = value; }
        }

        public PuntoDeAutorizacion(string sucursal, string caja)
        {
            this.sucursal = sucursal;
            this.caja = caja;
        }

        public PuntoDeAutorizacion()
        {
        }
    }
}
