//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.BusinessLogic
{
    public class Voucher
    {

        /*this.tktNumber = 0;
this.name = "";
this.issueDate = "";
this.totalFare = "";
this.currency = "";
this.agent = "";
this.city = "";
this.station = "";
this.tktAsoc = "";
this.flightInfo = "";
this.type = "";*/
        /// <summary>
        /// Cod Tarjeta para la transaccion
        /// </summary>
        /// 
        private string _issueDate;
        public string issueDate
        {
            get { return _issueDate; }
            set { _issueDate = value; }
        }


        private string _status;
        public string status
        {
            get { return _status; }
            set { _status = value; }
        }


        private string _descIngles;
        public string descIngles
        {
            get { return _descIngles; }
            set { _descIngles = value; }
        }

        private string _descEspanol;
        public string descEspanol
        {
            get { return _descEspanol; }
            set { _descEspanol = value; }
        }


        private string _type;
        public string type
        {
            get { return _type; }
            set { _type = value; }
        }

        private string _flightInfo;
        public string flightInfo
        {
            get { return _flightInfo; }
            set { _flightInfo = value; }
        }

        private string _tktAsoc;
        public string tktAsoc
        {
            get { return _tktAsoc; }
            set { _tktAsoc = value; }
        }

        private string _station;
        public string station
        {
            get { return _station; }
            set { _station = value; }
        }

        private string _city;
        public string city
        {
            get { return _city; }
            set { _city = value; }
        }

        private string _agent;
        public string agent
        {
            get { return _agent; }
            set { _agent = value; }
        }

        private string _currency;
        public string currency
        {
            get { return _currency; }
            set { _currency = value; }
        }

        private string _totalFare;
        public string totalFare
        {
            get { return _totalFare; }
            set { _totalFare = value; }
        }

        private string _tktNumber;
        public string tktNumber
        {
            get { return _tktNumber; }
            set { _tktNumber = value; }
        }

        private string _name;
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }


        private string _idVoucher;
        public string idVoucher
        {
            get { return _idVoucher; }
            set { _idVoucher = value; }
        }

    }
}

