//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.RespuestasPOS.Errores
{
    public enum CerrarTransaccion
	{
		VPI_ERR_COM = 301,
		VPI_ERR_PRINT = 302,
        NADA = 0,
	}
}
