//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.RespuestasPOS.Errores
{
    public enum Implementacion
	{
		VPI_INVALID_IN_CMD = 901,
		VPI_INVALID_IN_PARAM = 902,
		VPI_INVALID_OUT_CMD = 903,
		VPI_GENERAL_FAIL = 909,
        NADA = 0,
	}
}
