//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.RespuestasPOS.Errores
{
    public enum InicioTransaccion
	{
		VPI_TRX_CANCELLED = 201,
		VPI_DIF_CARD = 202,
		VPI_INVALID_CARD = 203,
		VPI_EXPIRED_CARD = 204,
		VPI_INVALID_TRX = 205,
		VPI_NO_TRANS_BATCH = 206,
        NADA = 0,
	}
}
