//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.RespuestasPOS.Errores
{
    public enum Parametros
	{
		VPI_INVALID_ISSUER = 101,
		VPI_INVALID_TICKET = 102,
		VPI_INVALID_PLAN = 103,
		VPI_INVALID_INDEX = 104,
		VPI_INVALID_BATCH = 105,
        NADA = 0,
	}
}
