using CodenameNightwing.Autorization.POS;
using CodenameNightwing.Autorization.VTOL;
using CodenameNightwing.BusinessLogic;
using CodenameNightwing.Config;
using CodenameNightwing.Printer.Models;
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenameNightwing.Autorization
{
    public static class PrinterModelFactory
    {
        public static PrinterModel getPrinterModel()
        {
            switch (Configuration.getInstance().tipoPrinter)
            {
                case TipoPrinter.EPSON:
                    return new PrinterEpson();
                case TipoPrinter.GPRINTER:
                    return new PrinterGPrinter();
                default:
                    return new PrinterGPrinter();
            }
        }
    }
}
