//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodenameNightwing.Autorization.POS.RespuestasPOS
{
    public enum Resultados
	{
		VPI_OK = 0,
		VPI_MORE_REC = 1,
		VPI_FAIL = 11,
		VPI_TIMEOUT_EXP = 12,
	}
}
